[package]
name = "Vanity-Address"
version = "0.1.0"
authors = ["Mitchell <17392435+MitchellBerry@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
num-bigint = { version = "0.2.2", features = ["rand"] }
sha2 = "0.8.0"
ed25519-dalek = "0.9.1"
base58 = "0.1.0"